nginx:
    build: ./nginx
    links:
        - node1:node1
    ports:
        - "80:80"
node1:
    build: ./node
    volumes:
        - ./node/.:/src
    environment:
        - POSTGRES_USER=youruser
        - POSTGRES_PASSWORD=yourpw
    links:
        - postgres
    ports:
        - "8080"
postgres:
    image: postgres
    environment:
        - POSTGRES_USER=youruser
        - POSTGRES_PASSWORD=yourpw
    ports:
        - "5432:5432"